from scenario_manager.world_factory import WorldFactory, RandomProperty
from agents.agent import Agent
from environment.objects.simple_objects import C4I, SeWaCo, Mobiliteit, Energy, Brand, Gewonde, Lekkage, Waypoint


def create_factory(seed=None):

    factory = WorldFactory(random_seed=seed, shape=[5, 5], tick_duration=0.5)

    random_prop = RandomProperty(values=["klein", "middelmatig", "groot"],
                                 distribution=[0.33, 0.33, 0.33])

    factory.add_env_object_prospect(location=[0, 0], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 0], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 0], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 0], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 0], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 1], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 1], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 1], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 1], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 1], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 2], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 2], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 2], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 2], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 2], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 3], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 3], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 3], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 3], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 3], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 4], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 4], name="C4I", callable_class=C4I, probability=0.1, omvang=random_prop)

    factory.add_env_object_prospect(location=[0, 0], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 0], name="Gewonde", callable_class=Gewonde, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 0], name="Gewonde", callable_class=Gewonde, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 0], name="Gewonde", callable_class=Gewonde, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 0], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 1], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 1], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 1], name="Gewonde", callable_class=Gewonde, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 1], name="Gewonde", callable_class=Gewonde, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 1], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 2], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 2], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 2], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 2], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 2], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 3], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 3], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 3], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 3], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 3], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 4], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 4], name="Gewonde", callable_class=Gewonde, probability=0.1, omvang=random_prop)

    factory.add_env_object_prospect(location=[0, 0], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 0], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 0], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 0], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 0], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 1], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 1], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 1], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 1], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 1], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 2], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 2], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 2], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 2], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 2], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 3], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 3], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 3], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 3], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 3], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="Brand", callable_class=Brand, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 4], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 4], name="Brand", callable_class=Brand, probability=0.1, omvang=random_prop)

    factory.add_env_object_prospect(location=[1, 0], name="SeWaCo", callable_class=SeWaCo, probability=0.4, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 0], name="SeWaCo", callable_class=SeWaCo, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 0], name="SeWaCo", callable_class=SeWaCo, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 1], name="SeWaCo", callable_class=SeWaCo, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 1], name="SeWaCo", callable_class=SeWaCo, probability=0.2, omvang=random_prop)

    factory.add_env_object_prospect(location=[0, 1], name="Energy", callable_class=Energy, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 1], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 1], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 1], name="Energy", callable_class=Energy, probability=0.4, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 2], name="Energy", callable_class=Energy, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 2], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 2], name="Energy", callable_class=Energy, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 3], name="Energy", callable_class=Energy, probability=0.7, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 3], name="Energy", callable_class=Energy, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 3], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="Energy", callable_class=Energy, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="Energy", callable_class=Energy, probability=0.1, omvang=random_prop)

    factory.add_env_object_prospect(location=[0, 3], name="Lekkage", callable_class=Lekkage, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 3], name="Lekkage", callable_class=Lekkage, probability=0.1, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 3], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)   
    factory.add_env_object_prospect(location=[3, 3], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 3], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[3, 4], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)
    factory.add_env_object_prospect(location=[4, 4], name="Lekkage", callable_class=Lekkage, probability=0.2, omvang=random_prop)

    factory.add_env_object_prospect(location=[1, 3], name="Mobiliteit", callable_class=Mobiliteit, probability=0.4, omvang=random_prop)
    factory.add_env_object_prospect(location=[0, 4], name="Mobiliteit", callable_class=Mobiliteit, probability=0.3, omvang=random_prop)
    factory.add_env_object_prospect(location=[1, 4], name="Mobiliteit", callable_class=Mobiliteit, probability=0.5, omvang=random_prop)
    factory.add_env_object_prospect(location=[2, 4], name="Mobiliteit", callable_class=Mobiliteit, probability=0.5, omvang=random_prop)
    
    factory.add_env_object(location=[0, 0], name="Route 1-0", route_name="Route 1", waypoint_number=0, callable_class=Waypoint, visualization_colour="#f44242")
    factory.add_env_object(location=[0, 1], name="Route 1-1", route_name="Route 1", waypoint_number=1, callable_class=Waypoint, visualization_colour="#f44242")
    factory.add_env_object(location=[0, 2], name="Route 1-2", route_name="Route 1", waypoint_number=2, callable_class=Waypoint, visualization_colour="#f44242")
    factory.add_env_object(location=[0, 3], name="Route 1-3", route_name="Route 1", waypoint_number=3, callable_class=Waypoint, visualization_colour="#f44242")
    factory.add_env_object(location=[1, 2], name="Route 1-4", route_name="Route 1", waypoint_number=4, callable_class=Waypoint, visualization_colour="#f44242")

    factory.add_env_object(location=[1, 0], name="Route 2-0", route_name="Route 2", waypoint_number=0, callable_class=Waypoint, visualization_colour="#f4f141")
    factory.add_env_object(location=[2, 0], name="Route 2-1", route_name="Route 2", waypoint_number=1, callable_class=Waypoint, visualization_colour="#f4f141")
    factory.add_env_object(location=[3, 0], name="Route 2-2", route_name="Route 2", waypoint_number=2, callable_class=Waypoint, visualization_colour="#f4f141")
    factory.add_env_object(location=[2, 1], name="Route 2-3", route_name="Route 2", waypoint_number=3, callable_class=Waypoint, visualization_colour="#f4f141")
    factory.add_env_object(location=[1, 1], name="Route 2-4", route_name="Route 2", waypoint_number=4, callable_class=Waypoint, visualization_colour="#f4f141")

    factory.add_env_object(location=[4, 0], name="Route 3-0", route_name="Route 3", waypoint_number=0, callable_class=Waypoint, visualization_colour="#5bf441")
    factory.add_env_object(location=[4, 1], name="Route 3-1", route_name="Route 3", waypoint_number=1, callable_class=Waypoint, visualization_colour="#5bf441")
    factory.add_env_object(location=[4, 2], name="Route 3-2", route_name="Route 3", waypoint_number=2, callable_class=Waypoint, visualization_colour="#5bf441")
    factory.add_env_object(location=[3, 1], name="Route 3-3", route_name="Route 3", waypoint_number=3, callable_class=Waypoint, visualization_colour="#5bf441")
    factory.add_env_object(location=[3, 2], name="Route 3-4", route_name="Route 3", waypoint_number=4, callable_class=Waypoint, visualization_colour="#5bf441")

    factory.add_env_object(location=[0, 4], name="Route 4-0", route_name="Route 4", waypoint_number=0, callable_class=Waypoint, visualization_colour="#41d6f4")
    factory.add_env_object(location=[1, 4], name="Route 4-1", route_name="Route 4", waypoint_number=1, callable_class=Waypoint, visualization_colour="#41d6f4")
    factory.add_env_object(location=[2, 4], name="Route 4-2", route_name="Route 4", waypoint_number=2, callable_class=Waypoint, visualization_colour="#41d6f4")
    factory.add_env_object(location=[1, 3], name="Route 4-3", route_name="Route 4", waypoint_number=3, callable_class=Waypoint, visualization_colour="#41d6f4")
    factory.add_env_object(location=[2, 3], name="Route 4-4", route_name="Route 4", waypoint_number=4, callable_class=Waypoint, visualization_colour="#41d6f4")

    factory.add_env_object(location=[3, 4], name="Route 5-0", route_name="Route 5", waypoint_number=0, callable_class=Waypoint, visualization_colour="#eb41f4")
    factory.add_env_object(location=[4, 4], name="Route 5-1", route_name="Route 5", waypoint_number=1, callable_class=Waypoint, visualization_colour="#eb41f4")
    factory.add_env_object(location=[4, 3], name="Route 5-2", route_name="Route 5", waypoint_number=2, callable_class=Waypoint, visualization_colour="#eb41f4")
    factory.add_env_object(location=[3, 3], name="Route 5-3", route_name="Route 5", waypoint_number=3, callable_class=Waypoint, visualization_colour="#eb41f4")
    factory.add_env_object(location=[2, 2], name="Route 5-4", route_name="Route 5", waypoint_number=4, callable_class=Waypoint, visualization_colour="#eb41f4")

    agent = Agent()  # Change to BS agent
    factory.add_agent(location=[1, 0], agent=agent)

    return factory